export const screeNames ={
    LoginScreen:'LoginScreen',
    InitialScreen:'InitialScreen',
    ProductsScreen:'ProducstScreen',
    DashboardScreen:'DashboardScreen',
    EnquiryScreen:'EnquiryScreen',
    DeliveryChallanScreen:'DeliveryChallanScreen',
    JobCardsScreen:'JobCardsScreen',
    QuatationsScreen:'QuatationsScreen',
    AccessManagementScreen:'AccessManagementScreen',
    ComplaintsScreen:'ComplaintsScreen',
    AddEnquiriesScreen:'AddEnquiriesScreen',
    AddQuotationScreen:'AddQuotationScreen',
    AddComplaintScreen:'AddComplaintScreen',
    AddDeliveryChallan:'AddDeliveryChallanScreen',
}